name: Main
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Merge
        run: |
          git config --global user.name 'Jonathan Brink'
          git config --global user.email 'jonbri@users.noreply.github.com'
          git checkout main
          git merge --no-ff prod
      - name: PR
        uses: peter-evans/create-pull-request@v5

